### ISSUE TITLE
albatross.deb for ubuntu 22.04

### ISSUE THREAD

**Issue by nickbetteridge** [roburio/albatross#122]
I've been playing around with the debian packaging that @reynir has provided.

Firstly, just let me say that I'm no linux expert!

1. I cloned albatross, did a ```dune build```
2. I edited 'albatross/packaging/debian/control' and updated %%VERSION%% to the current version - not too sure how to automate this
3. sh -ex packaging/debian/create_package.sh
4. sudo dpkg -i ./albatross.deb
5. sudo apt install -f
6. sudo systemctl enable albatross_daemon.service  , etc

Deploying unikernels didn't work and I discovered that, for example, trying to deploy a hvt locally resulted in albatross-client-local trying to execute solo5-hvt in /var/lib/albatross, whereas the albatross binaries had been installed in /usr/bin.

I guess the packaging scripts are really meant for user customisation. Nevertheless, using albatross is a dream - thanks for making it available.

The following ubuntu netplan is for setting up a static host ip address with a service bridge for albatross - just in case it's useful for anyone

```
network:
  version: 2
  renderer: networkd

  ethernets:
    enpXXX:
      dhcp4: false
      dhcp6: false

  bridges:
    service:
      interfaces: [enpXXX]
      addresses: [10.0.0.XXX/24]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 10.0.0.1
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [1.1.1.1,1.0.0.1]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no
```
where ```enpXXX``` is the exposed interface and ```10.0.0.XXX/24``` is the static IP for the host
